/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyGui;

/**
 *
 * @author Gabriel Sioson
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        this("ADMIN", "Admin");
    }
    
    public MainFrame(String role, String username) {
        setTitle("Terralith Estate");
        initComponents();
        setLocationRelativeTo(null);
        applyRole(role, username);
    }
    
    private void applyRole(String role, String username) {
        switch (role) {
            case "GUEST":
                // Guest/Client: View Lots only
                ReserveLot.setVisible(false);
                SellLot.setVisible(false);
                GenerateReport.setVisible(false);
                TransactionLog.setVisible(false);
                PayInstallment.setVisible(false);
                setTitle("Terralith Estate  —  Guest");
                break;
            case "AGENT":
                // Agent: View, Reserve, Sell, Pay Installment
                GenerateReport.setVisible(false);
                TransactionLog.setVisible(false);
                setTitle("Terralith Estate  —  Agent: " + username);
                break;
            case "ADMIN":
            default:
                // Admin: full access — nothing hidden
                setTitle("Terralith Estate  —  Admin");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        ViewLots = new javax.swing.JButton();
        ReserveLot = new javax.swing.JButton();
        SellLot = new javax.swing.JButton();
        GenerateReport = new javax.swing.JButton();
        TransactionLog = new javax.swing.JButton();
        PayInstallment = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyGui/Images/Logo.png"))); // NOI18N

        jLabel2.setText("Real Estate Management System");

        ViewLots.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewLots.setText("View Lots");
        ViewLots.addActionListener(this::ViewLotsActionPerformed);

        ReserveLot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ReserveLot.setText("Reserve a Lot");
        ReserveLot.addActionListener(this::ReserveLotActionPerformed);

        SellLot.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SellLot.setText("Sell a Lot");
        SellLot.addActionListener(this::SellLotActionPerformed);

        GenerateReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GenerateReport.setText("Generate Report");
        GenerateReport.addActionListener(this::GenerateReportActionPerformed);

        TransactionLog.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TransactionLog.setText("Transaction Log");
        TransactionLog.addActionListener(this::TransactionLogActionPerformed);

        PayInstallment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PayInstallment.setText("Pay Installment");
        PayInstallment.addActionListener(this::PayInstallmentActionPerformed);

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ViewLots, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ReserveLot, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(SellLot, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(TransactionLog, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(PayInstallment, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addComponent(ViewLots, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReserveLot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SellLot, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(TransactionLog, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(PayInstallment, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Logout");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButton1)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SellLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SellLotActionPerformed
        // TODO add your handling code here:
        new SellLotFrame().setVisible(true);
    }//GEN-LAST:event_SellLotActionPerformed

    private void ReserveLotActionPerformed(java.awt.event.ActionEvent evt) {
        new ReserveLotFrame().setVisible(true);
    }

    private void TransactionLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionLogActionPerformed
        // TODO add your handling code here:
        new TransactionLogFrame().setVisible(true);
    }//GEN-LAST:event_TransactionLogActionPerformed

    private void ViewLotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewLotsActionPerformed
        // TODO add your handling code here:
        new ViewLotFrame().setVisible(true);
    }//GEN-LAST:event_ViewLotsActionPerformed

    private void GenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportActionPerformed
        // TODO add your handling code here:
        new ReportFrame().setVisible(true);
    }//GEN-LAST:event_GenerateReportActionPerformed

    private void PayInstallmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayInstallmentActionPerformed
        // TODO add your handling code here:
        new PayInstallmentFrame().setVisible(true);
    }//GEN-LAST:event_PayInstallmentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            for (java.awt.Window window : java.awt.Window.getWindows()) {
                if (window != this) {
                    window.dispose();
                }
            }
            new AdminLoginFrame().setVisible(true);
            dispose(); // finally close MainFrame itself
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateReport;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton PayInstallment;
    private javax.swing.JButton ReserveLot;
    private javax.swing.JButton SellLot;
    private javax.swing.JButton TransactionLog;
    private javax.swing.JButton ViewLots;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
