/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyGui;

import MyLib.*;

/**
 *
 * @author Gabriel Sioson
 */
public class SellLotFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SellLotFrame.class.getName());

    /**
     * Creates new form SellLotFrame
     */
    public SellLotFrame() {
        setTitle("Sell Lot");
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        togglePaymentFields();
        loadBlocks();
        loadAgents();
        loadLots();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        block = new javax.swing.JComboBox<>();
        lot = new javax.swing.JComboBox<>();
        agent = new javax.swing.JComboBox<>();
        payment = new javax.swing.JComboBox<>();
        discount = new javax.swing.JTextField();
        sell = new javax.swing.JButton();
        close = new javax.swing.JButton();
        txtDuration = new javax.swing.JLabel();
        txtInterest = new javax.swing.JLabel();
        Duration = new javax.swing.JTextField();
        Interest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Client Name:");

        jLabel2.setText("Contact Info:");

        jLabel3.setText("Block:");

        jLabel4.setText("Lot:");

        jLabel5.setText("Agent:");

        jLabel6.setText("Payment Type:");

        txtDiscount.setText("Discount Rate:");

        block.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block 1", "Block 2", "Block 3", "Block 4", "Block 5", " " }));

        lot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Installment", " " }));
        payment.addActionListener(this::paymentActionPerformed);

        sell.setText("Sell");
        sell.addActionListener(this::sellActionPerformed);

        close.setText("Close");
        close.addActionListener(this::closeActionPerformed);

        txtDuration.setText("Duration (months):");

        txtInterest.setText("Interest Rate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtDuration)
                            .addComponent(txtInterest))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name)
                            .addComponent(discount)
                            .addComponent(contact)
                            .addComponent(block, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payment, 0, 196, Short.MAX_VALUE)
                            .addComponent(Duration)
                            .addComponent(Interest)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(sell)
                        .addGap(43, 43, 43)
                        .addComponent(close)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiscount)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuration)
                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInterest)
                    .addComponent(Interest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sell)
                    .addComponent(close))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        togglePaymentFields();
    }//GEN-LAST:event_paymentActionPerformed

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // TODO add your handling code here:
        processSale();
    }//GEN-LAST:event_sellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SellLotFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Duration;
    private javax.swing.JTextField Interest;
    private javax.swing.JComboBox<String> agent;
    private javax.swing.JComboBox<String> block;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField discount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> lot;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> payment;
    private javax.swing.JButton sell;
    private javax.swing.JLabel txtDiscount;
    private javax.swing.JLabel txtDuration;
    private javax.swing.JLabel txtInterest;
    // End of variables declaration//GEN-END:variables

    private void togglePaymentFields() {
        boolean isCash = "Cash".equals(payment.getSelectedItem());
        txtDiscount.setVisible(isCash);
        discount.setVisible(isCash);
        txtDuration.setVisible(!isCash);
        Duration.setVisible(!isCash);
        txtInterest.setVisible(!isCash);
        Interest.setVisible(!isCash);
    }
    
    private void loadBlocks() {
        block.removeAllItems();
        for (Block b : Agency.getInstance().getMainProperty().getBlocks()) {
            block.addItem("Block " + b.getBlockNumber());
            }
        }

        private void loadLots() {
        lot.removeAllItems();

        if (block.getSelectedItem() == null) {
            return;
        }

        int blockNum = block.getSelectedIndex() + 1;
        Block b = Agency.getInstance().getMainProperty().getBlock(blockNum);

        for (Lot l : b.getLots()) {
            if (l.getStatus() != Lot.SOLD) {
                lot.addItem("Lot " + l.getLotNumber()
                        + " [" + l.getStatus() + "]"
                        + " | PHP " + String.format("%.2f", l.getPrice()));
            }
        }

        if (lot.getItemCount() == 0) {
            lot.addItem("No lots available");
        }
    }
        
    private void loadAgents() {
        agent.removeAllItems();
        for (Agent a : Agency.getInstance().getAgents()) {
            agent.addItem(a.getName());
        }
    }    
    
    private void processSale() {
        String clientName = name.getText().trim();
        String clientContact = contact.getText().trim();

        if (clientName.isEmpty() || clientContact.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (lot.getSelectedItem() == null || lot.getSelectedItem().toString().startsWith("No")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No lots available.");
            return;
        }

        int blockNum = block.getSelectedIndex() + 1;
        Block b = Agency.getInstance().getMainProperty().getBlock(blockNum);

        String lotText = (String) lot.getSelectedItem();
        int lotNum = Integer.parseInt(lotText.split(" ")[1]);

        Lot selectedLot = b.getLot(lotNum);

        Agency agency = Agency.getInstance();
        Client client = agency.findClientByName(clientName);

        if (client == null) {
            client = new Client(clientName, clientContact);
            agency.addClient(client);
        }

        Payment paymentMethod;
        double resFee = 5000;
        double closeFee = 3000;

        try {

            if ("Cash".equals(payment.getSelectedItem())) {

                double disc = Double.parseDouble(discount.getText().trim());
                paymentMethod = new Cash(selectedLot.getPrice(), resFee, closeFee, disc);

            } else {

                int months = Integer.parseInt(Duration.getText().trim());
                double interest = Double.parseDouble(Interest.getText().trim());

                paymentMethod = new Installment(selectedLot.getPrice(), resFee, closeFee, months, interest);
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number in payment fields.");
            return;
        }

        Agent selectedAgent = agency.getAgents().get(agent.getSelectedIndex());

        Transaction trans = selectedAgent.processSelling(client, selectedLot, paymentMethod);

        if (trans != null) {

            agency.addTransaction(trans);

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Sale Successful!\n"
                    + "Transaction ID: " + trans.getTransactionId() + "\n\n"
                    + paymentMethod.getPaymentSummary());

            name.setText("");
            contact.setText("");

            loadLots();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Lot is already sold.");
        }
    }
}
