/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MyGui;

import MyLib.*;

/**
 *
 * @author Gabriel Sioson
 */
public class SellLotFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SellLotFrame.class.getName());

    /**
     * Creates new form SellLotFrame
     */
    public SellLotFrame() {
        setTitle("Sell Lot");
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        togglePaymentFields();
        loadBlocks();
        loadAgents();
        loadLots();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        block = new javax.swing.JComboBox<>();
        lot = new javax.swing.JComboBox<>();
        agent = new javax.swing.JComboBox<>();
        payment = new javax.swing.JComboBox<>();
        sell = new javax.swing.JButton();
        close = new javax.swing.JButton();
        txtDuration = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        discount = new javax.swing.JComboBox<>();
        Duration = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Client Name:");

        jLabel2.setText("Contact Info:");

        jLabel3.setText("Block:");

        jLabel4.setText("Lot:");

        jLabel5.setText("Agent:");

        jLabel6.setText("Payment Type:");

        txtDiscount.setText("Discount Rate:");

        block.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Block 1", "Block 2", "Block 3", "Block 4", "Block 5", " " }));
        block.addActionListener(this::blockActionPerformed);

        lot.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        payment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Installment", " " }));
        payment.addActionListener(this::paymentActionPerformed);

        sell.setBackground(new java.awt.Color(0, 102, 0));
        sell.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sell.setForeground(new java.awt.Color(255, 255, 255));
        sell.setText("Sell");
        sell.addActionListener(this::sellActionPerformed);

        close.setBackground(new java.awt.Color(153, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setText("Close");
        close.addActionListener(this::closeActionPerformed);

        txtDuration.setText("Duration (months):");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyGui/Images/Logo.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        discount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1%", "2%", "3%", "5%", "10%" }));

        Duration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 years", "10 years", "15 years", "20 years ", "25 years", "30 years" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contact)
                            .addComponent(block, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(agent, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(payment, 0, 302, Short.MAX_VALUE)
                            .addComponent(name)
                            .addComponent(lot, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(discount, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Duration, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(sell, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(block, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(agent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiscount)
                    .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDuration)
                    .addComponent(Duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sell, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void paymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentActionPerformed
        // TODO add your handling code here:
        togglePaymentFields();
    }//GEN-LAST:event_paymentActionPerformed

    private void lotActionPerformed(java.awt.event.ActionEvent evt) {
        autoFillReserver();
    }

    private void sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellActionPerformed
        // TODO add your handling code here:
        processSale();
    }//GEN-LAST:event_sellActionPerformed

    private void blockActionPerformed(java.awt.event.ActionEvent evt) {
        loadLots();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SellLotFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Duration;
    private javax.swing.JComboBox<String> agent;
    private javax.swing.JComboBox<String> block;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> discount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> lot;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> payment;
    private javax.swing.JButton sell;
    private javax.swing.JLabel txtDiscount;
    private javax.swing.JLabel txtDuration;
    // End of variables declaration//GEN-END:variables

    private void togglePaymentFields() {
        boolean isCash = "Cash".equals(payment.getSelectedItem());
        txtDiscount.setVisible(isCash);
        discount.setVisible(isCash);
        txtDuration.setVisible(!isCash);
        Duration.setVisible(!isCash);
    }
    
    private void loadBlocks() {
        block.removeAllItems();
        for (Block b : Agency.getInstance().getMainProperty().getBlocks()) {
            block.addItem("Block " + b.getBlockNumber());
        }
    }

    private void loadLots() {
        // Temporarily remove listener to avoid firing during repopulation
        lot.removeActionListener(this::lotActionPerformed);
        lot.removeAllItems();

        if (block.getSelectedItem() == null) {
            lot.addActionListener(this::lotActionPerformed);
            resetNameField();
            return;
        }

        int blockNum = Integer.parseInt(((String) block.getSelectedItem()).split(" ")[1]);
        Block b = Agency.getInstance().getMainProperty().getBlock(blockNum);

        for (Lot l : b.getLots()) {
            if (!l.getStatus().equals(Lot.SOLD)) {
                String label = "Lot " + l.getLotNumber()
                        + " [" + l.getStatus() + "]"
                        + " | " + l.getModelName()
                        + " | PHP " + String.format("%,.2f", l.getPrice());

                if (l.getStatus().equals(Lot.RESERVED) && l.getOwner() != null) {
                    label += " | Reserved by: " + l.getOwner().getName();
                }

                lot.addItem(label);
            }
        }

        if (lot.getItemCount() == 0) {
            lot.addItem("No lots available");
        }

        // Re-attach listener then manually trigger
        lot.addActionListener(this::lotActionPerformed);
        autoFillReserver();
    }

    private void resetNameField() {
        name.setText("");
        name.setEditable(true);
    }

    private void autoFillReserver() {
        if (lot.getSelectedItem() == null
                || lot.getSelectedItem().toString().startsWith("No")) {
            resetNameField();
            return;
        }

        try {
            int blockNum = Integer.parseInt(((String) block.getSelectedItem()).split(" ")[1]);
            Block b = Agency.getInstance().getMainProperty().getBlock(blockNum);
            String lotText = (String) lot.getSelectedItem();
            int lotNum = Integer.parseInt(lotText.split(" ")[1]);
            Lot selectedLot = b.getLot(lotNum);

            if (selectedLot != null
                    && selectedLot.getStatus().equals(Lot.RESERVED)
                    && selectedLot.getOwner() != null) {
                name.setText(selectedLot.getOwner().getName());
                name.setEditable(false);
            } else {
                resetNameField();
            }
        } catch (NumberFormatException e) {
            resetNameField();
        }
    }
        
    private void loadAgents() {
        agent.removeAllItems();
        for (Agent a : Agency.getInstance().getAgents()) {
            agent.addItem(a.getName());
        }
    }    
    
    private void processSale() {
        String clientName = name.getText().trim();
        String clientContact = contact.getText().trim();

        if (clientName.isEmpty() || clientContact.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (lot.getSelectedItem() == null || lot.getSelectedItem().toString().startsWith("No")) {
            javax.swing.JOptionPane.showMessageDialog(this, "No lots available.");
            return;
        }

        int blockNum = Integer.parseInt(((String) block.getSelectedItem()).split(" ")[1]);
        Block b = Agency.getInstance().getMainProperty().getBlock(blockNum);

        String lotText = (String) lot.getSelectedItem();
        int lotNum = Integer.parseInt(lotText.split(" ")[1]);

        Lot selectedLot = b.getLot(lotNum);

        Agency agency = Agency.getInstance();
        Client client = agency.findClientByName(clientName);

        if (client == null) {
            client = new Client(clientName, clientContact);
            agency.addClient(client);
        }

        Payment paymentMethod;

        try {

            if ("Cash".equals(payment.getSelectedItem())) {
                // Cash: user enters a discount rate (e.g. 0.05 = 5%)
                String discStr = (String) discount.getSelectedItem();
                double discRate = Double.parseDouble(discStr.replace("%", "")) / 100.0;
                paymentMethod = new Cash(
                    selectedLot.getTotalContractPrice(),
                    selectedLot.getReservationFee(),
                    selectedLot.getNetDownPayment(),
                    discRate
                );

            } else {
                // Installment: duration in months entered by user
                // Interest rate is fixed from the lot (from PDF data)
                String durStr = (String) Duration.getSelectedItem();
                int months = Integer.parseInt(durStr.split(" ")[0]) * 12;
                paymentMethod = new Installment(
                    selectedLot.getLoanableAmount(),
                    selectedLot.getReservationFee(),
                    selectedLot.getNetDownPayment(),
                    months,
                    selectedLot.getInterestRate()
                );
            }

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid number in payment fields.");
            return;
        }

        Agent selectedAgent = agency.getAgents().get(agent.getSelectedIndex());
        Transaction trans = selectedAgent.processSelling(client, selectedLot, paymentMethod);

        if (trans != null) {

            agency.addTransaction(trans);

            // Build full payment summary based on PDF breakdown
            String summary =
                "=== PAYMENT BREAKDOWN ===\n"
                + String.format("House Model                  : %s\n", selectedLot.getModelName())
                + String.format("Selling Price                : PHP %,.2f\n", selectedLot.getSellingPrice())
                + String.format("Add: Legal & Misc Fees (5%%) : PHP %,.2f\n", selectedLot.getLegalAndMiscFees())
                + String.format("Total Contract Price (TCP)   : PHP %,.2f\n\n", selectedLot.getTotalContractPrice())
                + "=== SCHEDULE OF PAYMENT ===\n"
                + String.format("Required Down Payment (%.0f%%) : PHP %,.2f\n", selectedLot.getDownPaymentPercent() * 100, selectedLot.getRequiredDownPayment())
                + String.format("Less: Reservation Fee        : PHP %,.2f\n", selectedLot.getReservationFee())
                + String.format("Net Down Payment             : PHP %,.2f\n", selectedLot.getNetDownPayment())
                + String.format("Monthly Down Payment (%d mos) : PHP %,.2f\n\n", selectedLot.getDownPaymentTermMonths(), selectedLot.getMonthlyDownPayment())
                + "=== MONTHLY AMORTIZATION @ " + String.format("%.1f%%", selectedLot.getInterestRate() * 100) + " ===\n"
                + String.format("Loanable Amount    : PHP %,.2f\n", selectedLot.getLoanableAmount())
                + String.format("30 years           : PHP %,.2f\n", selectedLot.getMonthlyAmortization(30))
                + String.format("25 years           : PHP %,.2f\n", selectedLot.getMonthlyAmortization(25))
                + String.format("20 years           : PHP %,.2f\n", selectedLot.getMonthlyAmortization(20))
                + String.format("15 years           : PHP %,.2f\n", selectedLot.getMonthlyAmortization(15))
                + String.format("10 years           : PHP %,.2f\n", selectedLot.getMonthlyAmortization(10))
                + String.format("5 years            : PHP %,.2f\n", selectedLot.getMonthlyAmortization(5));

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Sale Successful!\n"
                    + "Transaction ID: " + trans.getTransactionId() + "\n\n"
                    + summary);

            name.setText("");
            name.setEditable(true);
            contact.setText("");
            loadLots();

        } else {
            if (selectedLot.getStatus().equals(Lot.RESERVED)) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "This lot is reserved by " + selectedLot.getOwner().getName() + ".\n"
                    + "Only the reserving client can complete the purchase.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Lot is already sold.");
            }
        }
    }
}
